package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Backup generated by hbm2java
 */
public class Backup  implements java.io.Serializable {


     private Integer index;
     private Date date;
     private String filename;

    public Backup() {
    }

    public Backup(Date date, String filename) {
       this.date = date;
       this.filename = filename;
    }
   
    public Integer getIndex() {
        return this.index;
    }
    
    public void setIndex(Integer index) {
        this.index = index;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }




}


