package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Balance generated by hbm2java
 */
public class Balance  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Integer year;
     private Double balance;
     private Date insertdate;

    public Balance() {
    }

	
    public Balance(String type) {
        this.type = type;
    }
    public Balance(String type, Integer year, Double balance, Date insertdate) {
       this.type = type;
       this.year = year;
       this.balance = balance;
       this.insertdate = insertdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Date getInsertdate() {
        return this.insertdate;
    }
    
    public void setInsertdate(Date insertdate) {
        this.insertdate = insertdate;
    }




}


