package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1



/**
 * Drawtypes generated by hbm2java
 */
public class Drawtypes  implements java.io.Serializable {


     private Integer drawtypeid;
     private String drawtypes;

    public Drawtypes() {
    }

    public Drawtypes(String drawtypes) {
       this.drawtypes = drawtypes;
    }
   
    public Integer getDrawtypeid() {
        return this.drawtypeid;
    }
    
    public void setDrawtypeid(Integer drawtypeid) {
        this.drawtypeid = drawtypeid;
    }
    public String getDrawtypes() {
        return this.drawtypes;
    }
    
    public void setDrawtypes(String drawtypes) {
        this.drawtypes = drawtypes;
    }




}


