package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Drawdetails generated by hbm2java
 */
public class Drawdetails  implements java.io.Serializable {


     private Integer drawdetailsid;
     private Integer memberid;
     private Integer term;
     private Date drawdate;
     private Integer drawtypeid;
     private Double amount;

    public Drawdetails() {
    }

    public Drawdetails(Integer memberid, Integer term, Date drawdate, Integer drawtypeid, Double amount) {
       this.memberid = memberid;
       this.term = term;
       this.drawdate = drawdate;
       this.drawtypeid = drawtypeid;
       this.amount = amount;
    }
   
    public Integer getDrawdetailsid() {
        return this.drawdetailsid;
    }
    
    public void setDrawdetailsid(Integer drawdetailsid) {
        this.drawdetailsid = drawdetailsid;
    }
    public Integer getMemberid() {
        return this.memberid;
    }
    
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }
    public Date getDrawdate() {
        return this.drawdate;
    }
    
    public void setDrawdate(Date drawdate) {
        this.drawdate = drawdate;
    }
    public Integer getDrawtypeid() {
        return this.drawtypeid;
    }
    
    public void setDrawtypeid(Integer drawtypeid) {
        this.drawtypeid = drawtypeid;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }




}


