package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer employeeid;
     private String employeeno;
     private String name;
     private String contactno;
     private String address;
     private Date joindate;
     private Date cfeateddate;

    public Employees() {
    }

    public Employees(String employeeno, String name, String contactno, String address, Date joindate, Date cfeateddate) {
       this.employeeno = employeeno;
       this.name = name;
       this.contactno = contactno;
       this.address = address;
       this.joindate = joindate;
       this.cfeateddate = cfeateddate;
    }
   
    public Integer getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
    public String getEmployeeno() {
        return this.employeeno;
    }
    
    public void setEmployeeno(String employeeno) {
        this.employeeno = employeeno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getJoindate() {
        return this.joindate;
    }
    
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }
    public Date getCfeateddate() {
        return this.cfeateddate;
    }
    
    public void setCfeateddate(Date cfeateddate) {
        this.cfeateddate = cfeateddate;
    }




}


