package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1



/**
 * Groupdrawdetails generated by hbm2java
 */
public class Groupdrawdetails  implements java.io.Serializable {


     private Integer groupdrawdetailsid;
     private Integer drawtypeid;
     private Integer groupid;

    public Groupdrawdetails() {
    }

    public Groupdrawdetails(Integer drawtypeid, Integer groupid) {
       this.drawtypeid = drawtypeid;
       this.groupid = groupid;
    }
   
    public Integer getGroupdrawdetailsid() {
        return this.groupdrawdetailsid;
    }
    
    public void setGroupdrawdetailsid(Integer groupdrawdetailsid) {
        this.groupdrawdetailsid = groupdrawdetailsid;
    }
    public Integer getDrawtypeid() {
        return this.drawtypeid;
    }
    
    public void setDrawtypeid(Integer drawtypeid) {
        this.drawtypeid = drawtypeid;
    }
    public Integer getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }




}


