package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * Members generated by hbm2java
 */
public class Members implements java.io.Serializable {

    private Integer memberid;
    private String membername;
    private String memberaddress;
    private String contactno;
    private String emailid;
    private int groupid;
    private boolean completed;
    private Date joindate;
    private int memberno;
    private String status;
    private String remarks;

    public Members() {
    }

    public Members(String contactno, String emailid, int groupid, boolean completed, Date joindate, int memberno) {
        this.contactno = contactno;
        this.emailid = emailid;
        this.groupid = groupid;
        this.completed = completed;
        this.joindate = joindate;
        this.memberno = memberno;
    }

    public Members(String membername, String memberaddress, String contactno, String emailid, int groupid, boolean completed, Date joindate, int memberno, String status, String remarks) {
        this.membername = membername;
        this.memberaddress = memberaddress;
        this.contactno = contactno;
        this.emailid = emailid;
        this.groupid = groupid;
        this.completed = completed;
        this.joindate = joindate;
        this.memberno = memberno;
        this.status = status;
        this.remarks = remarks;
    }

    public Integer getMemberid() {
        return this.memberid;
    }

    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    public String getMembername() {
        return this.membername;
    }

    public void setMembername(String membername) {
        this.membername = membername;
    }

    public String getMemberaddress() {
        return this.memberaddress;
    }

    public void setMemberaddress(String memberaddress) {
        this.memberaddress = memberaddress;
    }

    public String getContactno() {
        return this.contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    public String getEmailid() {
        return this.emailid;
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    public int getGroupid() {
        return this.groupid;
    }

    public void setGroupid(int groupid) {
        this.groupid = groupid;
    }

    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }

    public Date getJoindate() {
        return this.joindate;
    }

    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    public int getMemberno() {
        return this.memberno;
    }

    public void setMemberno(int memberno) {
        this.memberno = memberno;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
