package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1



/**
 * Paymentdetails generated by hbm2java
 */
public class Paymentdetails  implements java.io.Serializable {


     private Integer paymentdetailsid;
     private Integer paymentid;
     private Integer term;

    public Paymentdetails() {
    }

    public Paymentdetails(Integer paymentid, Integer term) {
       this.paymentid = paymentid;
       this.term = term;
    }
   
    public Integer getPaymentdetailsid() {
        return this.paymentdetailsid;
    }
    
    public void setPaymentdetailsid(Integer paymentdetailsid) {
        this.paymentdetailsid = paymentdetailsid;
    }
    public Integer getPaymentid() {
        return this.paymentid;
    }
    
    public void setPaymentid(Integer paymentid) {
        this.paymentid = paymentid;
    }
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }




}


