package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1



/**
 * Paymentmodes generated by hbm2java
 */
public class Paymentmodes  implements java.io.Serializable {


     private Integer paymentmodeid;
     private String paymentmode;

    public Paymentmodes() {
    }

    public Paymentmodes(String paymentmode) {
       this.paymentmode = paymentmode;
    }
   
    public Integer getPaymentmodeid() {
        return this.paymentmodeid;
    }
    
    public void setPaymentmodeid(Integer paymentmodeid) {
        this.paymentmodeid = paymentmodeid;
    }
    public String getPaymentmode() {
        return this.paymentmode;
    }
    
    public void setPaymentmode(String paymentmode) {
        this.paymentmode = paymentmode;
    }




}


