package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vouchers generated by hbm2java
 */
public class Vouchers  implements java.io.Serializable {


     private Integer voucherid;
     private String voucherno;
     private Date voucherdate;
     private String amount;
     private Double weight;
     private String remarks;
     private String vouchertype;
     private String vouchercategory;
     private Date createddate;
     private Date updateddate;

    public Vouchers() {
    }

    public Vouchers(String voucherno, Date voucherdate, String amount, Double weight, String remarks, String vouchertype, String vouchercategory, Date createddate, Date updateddate) {
       this.voucherno = voucherno;
       this.voucherdate = voucherdate;
       this.amount = amount;
       this.weight = weight;
       this.remarks = remarks;
       this.vouchertype = vouchertype;
       this.vouchercategory = vouchercategory;
       this.createddate = createddate;
       this.updateddate = updateddate;
    }
   
    public Integer getVoucherid() {
        return this.voucherid;
    }
    
    public void setVoucherid(Integer voucherid) {
        this.voucherid = voucherid;
    }
    public String getVoucherno() {
        return this.voucherno;
    }
    
    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }
    public Date getVoucherdate() {
        return this.voucherdate;
    }
    
    public void setVoucherdate(Date voucherdate) {
        this.voucherdate = voucherdate;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getVouchertype() {
        return this.vouchertype;
    }
    
    public void setVouchertype(String vouchertype) {
        this.vouchertype = vouchertype;
    }
    public String getVouchercategory() {
        return this.vouchercategory;
    }
    
    public void setVouchercategory(String vouchercategory) {
        this.vouchercategory = vouchercategory;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Date getUpdateddate() {
        return this.updateddate;
    }
    
    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }




}


