package mappings;
// Generated 9 Jul, 2017 4:43:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Workersmemo generated by hbm2java
 */
public class Workersmemo  implements java.io.Serializable {


     private Integer workersmemoid;
     private Integer workermemono;
     private String orderno;
     private Date date;
     private Date createddate;
     private String employee;
     private Double goldweight;
     private Double silverweight;
     private Double stoneweight;
     private Double diamondweight;
     private String remarks;
     private String jewel;
     private Date readydate;
     private Double netweight;
     private String size;

    public Workersmemo() {
    }

    public Workersmemo(Integer workermemono, String orderno, Date date, Date createddate, String employee, Double goldweight, Double silverweight, Double stoneweight, Double diamondweight, String remarks, String jewel, Date readydate, Double netweight, String size) {
       this.workermemono = workermemono;
       this.orderno = orderno;
       this.date = date;
       this.createddate = createddate;
       this.employee = employee;
       this.goldweight = goldweight;
       this.silverweight = silverweight;
       this.stoneweight = stoneweight;
       this.diamondweight = diamondweight;
       this.remarks = remarks;
       this.jewel = jewel;
       this.readydate = readydate;
       this.netweight = netweight;
       this.size = size;
    }
   
    public Integer getWorkersmemoid() {
        return this.workersmemoid;
    }
    
    public void setWorkersmemoid(Integer workersmemoid) {
        this.workersmemoid = workersmemoid;
    }
    public Integer getWorkermemono() {
        return this.workermemono;
    }
    
    public void setWorkermemono(Integer workermemono) {
        this.workermemono = workermemono;
    }
    public String getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public String getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(String employee) {
        this.employee = employee;
    }
    public Double getGoldweight() {
        return this.goldweight;
    }
    
    public void setGoldweight(Double goldweight) {
        this.goldweight = goldweight;
    }
    public Double getSilverweight() {
        return this.silverweight;
    }
    
    public void setSilverweight(Double silverweight) {
        this.silverweight = silverweight;
    }
    public Double getStoneweight() {
        return this.stoneweight;
    }
    
    public void setStoneweight(Double stoneweight) {
        this.stoneweight = stoneweight;
    }
    public Double getDiamondweight() {
        return this.diamondweight;
    }
    
    public void setDiamondweight(Double diamondweight) {
        this.diamondweight = diamondweight;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public String getJewel() {
        return this.jewel;
    }
    
    public void setJewel(String jewel) {
        this.jewel = jewel;
    }
    public Date getReadydate() {
        return this.readydate;
    }
    
    public void setReadydate(Date readydate) {
        this.readydate = readydate;
    }
    public Double getNetweight() {
        return this.netweight;
    }
    
    public void setNetweight(Double netweight) {
        this.netweight = netweight;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }




}


